version: '3.3'
services:
  frontend:
    build: ./TBSPRPG_UI/tbsprpg
    ports:
      - '4200:4200'
    volumes:
      - './TBSPRPG_UI/tbsprpg:/app'
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200
    depends_on:
      - publicapi

  publicapi:
    build: ./TBSPRPG_PAPI
    ports:
      - '8000:5000'
    volumes:
      - './TBSPRPG_PAPI/PublicApi:/app'
    environment:
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
    depends_on: 
      - adventureapi
      - userapi
      - gameapi
      - mapapi

  userapi:
    build: ./TBSPRPG_UserAPI
    ports:
      - '8001:8001'
    volumes:
      - './TBSPRPG_UserAPI/UserApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
      - 'Database__Salt=${DBSALT}'
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run

  adventureapi:
    build: ./TBSPRPG_AdventureAPI
    ports:
      - '8002:8002'
    volumes:
      - './TBSPRPG_AdventureAPI/AdventureApi:/app'
    environment:
      - CONNECTION_STRING=User ID=${POSTGRESUSER};Password=${POSTGRESPASSWORD};Server=${POSTGRESURL};Port=5432;Database=${POSTGRESUSER};Integrated Security=true;Pooling=true;
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run

  gameapi:
    build: ./TBSPRPG_GameAPI
    ports:
      - '8003:8003'
    volumes:
      - './TBSPRPG_GameAPI/GameApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
    depends_on:
      - eventstore

  mapapi:
    build: ./TBSPRPG_MapAPI
    ports:
      - '8004:8004'
    volumes:
      - './TBSPRPG_MapAPI/MapApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
    depends_on:
      - eventstore
      - adventureapi

  eventstore:
    image: eventstore/eventstore:latest
    ports:
      - "2113:2113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true

  frontend_node_modules:
    build: ./TBSPRPG_UI/tbsprpg
    ports:
      - '4200:4200'
    volumes:
      - './TBSPRPG_UI/tbsprpg:/app'
    command: npm install
