version: '3.3'
services:
  frontend:
    build: ./TBSPRPG_UI/tbsprpg
    ports:
      - '4200:4200'
    volumes:
      - './TBSPRPG_UI/tbsprpg:/app'
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200
    depends_on:
      - publicapi

  publicapi:
    build: ./TBSPRPG_PAPI/PublicApi
    ports:
      - '8000:8000'
    volumes:
      - './TBSPRPG_PAPI/PublicApi:/app'
    environment:
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
    depends_on: 
      - adventureapi
      - userapi

  userapi:
    build: ./TBSPRPG_UserAPI/UserApi
    #ports:
    #  - '8001:8001'
    volumes:
      - './TBSPRPG_UserAPI/UserApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
      - 'Database__Salt=${DBSALT}'
    command: dotnet watch run

  adventureapi:
    build: ./TBSPRPG_AdventureAPI/AdventureApi
    #ports:
    #  - '8002:8002'
    volumes:
      - './TBSPRPG_AdventureAPI/AdventureApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
    command: dotnet watch run

  frontend_node_modules:
    build: ./TBSPRPG_UI/tbsprpg
    ports:
      - '4200:4200'
    volumes:
      - './TBSPRPG_UI/tbsprpg:/app'
    command: npm install
