version: '3.3'
services:
  tbspapi:
    build: TbspApi
    ports:
      - '8000:8000'
    volumes:
      - './TbspApi:/app'
    environment:
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
