version: '3.3'
services:
  frontend:
    build: frontend
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/app'
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200

  publicapi:
    build: ./backend/PublicApi
    ports:
      - '8000:8000'
    volumes:
      - './backend/PublicApi:/app'
    environment:
      - 'JwtSettings__Secret=${JWTSECRET}'
    command: dotnet watch run
    depends_on: 
      - adventureapi
      - userapi

  userapi:
    build: ./backend/UserApi
    ports:
      - '8001:8001'
    volumes:
      - './backend/UserApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
      - 'Database__Salt=${DBSALT}'
    command: dotnet watch run

  adventureapi:
    build: ./backend/AdventureApi
    ports:
      - '8002:8002'
    volumes:
      - './backend/AdventureApi:/app'
    environment:
      - 'Database__Password=${DBPASSWORD}'
    command: dotnet watch run
